/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
// This pprogram is to set the adc bit number 8
//1. set the clk for the ADC
//2. set the 8th bit of the ADC reg
#include <stdint.h>

#define ADC_BASE_ADDR	0x40012000UL
#define ADC_CR1_REG_OFFSET	0x04UL
#define ADC_CR1_REG_ADDR	(ADC_BASE_ADDR + ADC_CR1_REG_OFFSET)

#define RCC_BASE_ADDR	0x40023800UL
#define RCC_APB2_ENR_OFF	0x44UL
#define RCC_APB2_ENR_REG_ADDR	(RCC_BASE_ADDR + RCC_APB2_ENR_OFF)

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	uint32_t *pAdcCr1Reg   = (uint32_t*) ADC_CR1_REG_ADDR;
	uint32_t *pRccApb2Enr  = (uint32_t*) RCC_APB2_ENR_REG_ADDR;



	//enable peri clock of ADC1
	*pRccApb2Enr |= (1 << 8);

	//modify the adc crl reg(this reg is taken as oart of example on how to modify
	//specific reg of ADC
	*pAdcCr1Reg |= (1 << 8);


    /* Loop forever */
	for(;;);
}
